### PR TITLE
More comprehensive error messages for checkout validation

### LINKED ISSUE #574: More verbose error messages on denied state changes during checkout
Currently if I want to complete an order and I haven't gone through defining a payment method all I get when calling `PUT /checkout/{cartToken}/complete` is:

```
{
    "code": 500,
    "message": "Order with {cartToken} token cannot be completed."
}
```

it would be very helpful to have a more verbose error message and maybe another code. As `500` somehow implies that there is a server error and somewhere you should be able to find a stacktrace or at least log entry.

A message like:

> Order with {cartToken} token cannot be completed. Please set a payment method first.

would be way clearer.

### PR DESCRIPTION
**Pull request by mamazu**
Closes #574

### CODE REVIEW

File: src/Validator/Cart/CartReadyForCheckoutValidator.php [hunk 1]
```diff
@@ -28,16 +30,36 @@ public function __construct(RepositoryInterface $cartRepository, FactoryInterfac
...
-        if (!$stateMachine->can(OrderCheckoutTransitions::TRANSITION_COMPLETE)) {
-            /** @var CartReadyForCheckout $constraint */
-            $this->context->addViolation($constraint->message);
+        if ($stateMachine->can(OrderCheckoutTransitions::TRANSITION_COMPLETE)) {
+            return;
         }
+
+        /** @var CartReadyForCheckout $constraint */
+        $validationMessage = $constraint->message;
+        switch ($cart->getState()) {
```
Comment (lchrusciel) [inline src/Validator/Cart/CartReadyForCheckoutValidator.php]: Wouldn't it be more granular if we would just create 4 different validators?

Comment (mamazu) [reply src/Validator/Cart/CartReadyForCheckoutValidator.php]: Yes, but then you'd have to have control over in which order they are validated. It doesn't make sense to return a response like payment method not chosen if the cart hasn't been addressed yet. What we could do however is make multiple constraints that are validated by the same validator. Because the logic of the validator is always the same. I am not so sure however if that is a good idea.

**Comment by lchrusciel** [comment]
Thanks, @mamazu! :1st_place_medal:
